### ISSUE TITLE
MissionFailed event not triggering

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#113] opened 2017-02-01 22:50 UTC
The mission failed event is not triggering in 2.1.1-b2.

This is from the log: 

`2017-02-01T22:47:21 JournalMonitor:ParseJournalEntry [D] Unhandled event: { "timestamp":"2017-02-01T22:47:21Z", "event":"MissionFailed", "Name":"Mission_Scan_War_name", "MissionID":82522029 } `

And here's the verbose log file: 
[eddi.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/746379/eddi.zip)

Thanks!!

**Comment by omega9380** [comment] 2017-02-01 22:57
To help, I checked the JournalMonitor.cs code under the feature/home branch here on Github.  If I am interpreting your code correctly, you have a select case for each of the possible journal triggers.  Well, if you check your code, there are cases for MissionAccepted, MissionCompleted, and MissionAbandoned, but no case for MissionFailed?  I'm probably reading it wrong, I'm not a C# coder, but I thought I would point it out.  Thanks!!!!

**Comment by cmdrmcdonald** [comment] 2017-02-02 09:18
duplicate of #107

**Closed by cmdrmcdonald** 2017-02-02 09:18 UTC
