### ISSUE TITLE
companion app error

### ISSUE THREAD

**Issue by rockopoulos** [cmdrmcdonald/EliteDangerousDataProvider#188] opened 2017-04-13 02:55 UTC
![image](https://cloud.githubusercontent.com/assets/27394944/24988307/1ab011fc-1fd3-11e7-9613-4561e7481215.png)

**Comment by TomasEkeli** [comment] 2017-04-13 18:32
Until a new release is made you can drop in a replacement-file for the CompanionApp -library as described in the readme in this zip: https://www.dropbox.com/sh/kvevq3u9qbi9mm5/AAAHgcMdqmLh7sR4ZSbJOuQba?dl=0&preview=EDDI_commanders_fix.zip

**Comment by commentluv** [comment] 2017-04-13 22:57
omg thanks for this info Tomas! I'm back!

**Comment by cmdrmcdonald** [comment] 2017-04-14 06:21
Duplicate of #179

**Closed by cmdrmcdonald** 2017-04-14 06:21 UTC
