### ISSUE TITLE
EDDI companion API failure

### ISSUE THREAD

**Issue by Stevax** [cmdrmcdonald/EliteDangerousDataProvider#179] opened 2017-04-11 18:14 UTC
Just updated to latest version, now cannot link to Frontier API
<img width="590" alt="capture" src="https://cloud.githubusercontent.com/assets/27301376/24923958/19292f3c-1eeb-11e7-8c10-772a8a4b243a.PNG">

**Comment by NicoFlows** [comment] 2017-04-11 18:31
+1 same problem same message

**Comment by nfxus** [comment] 2017-04-11 18:35
+1 Same here!

**Comment by ReverendRhyme** [comment] 2017-04-11 18:37
+1 Same issue
![capture](https://cloud.githubusercontent.com/assets/23423902/24924891/6fe78c46-1ec4-11e7-8911-2631b159d293.PNG)

**Comment by borranvrikel** [comment] 2017-04-11 18:56
same here

**Comment by Estelyen** [comment] 2017-04-11 19:01
Same message in german:
![eddi](https://cloud.githubusercontent.com/assets/27303632/24925913/13ce7a88-1efa-11e7-97e8-807d3d94e78e.jpg)

**Comment by carlostib** [comment] 2017-04-11 19:26
Exactly same issue? I reinstalled EDDI cause I changed mobo so I'm resintalling everything, and when I try to set the Companion App from EDDI, same message appears:
![eddi_companion_app_issue](https://cloud.githubusercontent.com/assets/6964791/24926941/e2c89d92-1ec2-11e7-9b8b-fc830b23575e.jpg)

**Comment by bradsr132** [comment] 2017-04-11 19:36
same here

**Comment by Heisenberch** [comment] 2017-04-11 19:56
same here , 
but thanks for your work all the time !

**Comment by The1AndMany** [comment] 2017-04-11 20:20
Same here.

**Comment by Darkcyde13** [comment] 2017-04-11 21:18
EDDI wouldn't even load for me anymore.  It started, I could see it in the Task Manager, but before the EDDI screen appeared, the whole thing just quit.

However, deleting my credentials.json, allows it to run again.  And now I get the same error as everyone else.

**Comment by vinman75** [comment] 2017-04-11 21:48
Same here for me.

**Comment by awp3rator** [comment] 2017-04-11 22:50
Same issues as above.  I had another ticket open with full logging info in it.  EDDI 2.2.2 Crash on Startup with Elite 2.3 Patch #180

**Comment by SlashmanSG** [comment] 2017-04-11 23:02
Same here, sucks because I'm _not_ playing ED without it.

**Comment by folkdeezy** [comment] 2017-04-11 23:18
yeah cant get it to recognize me, now it wont even open

**Comment by rhedrock** [comment] 2017-04-12 00:06
Same issue, same screenshot as the first post; here's what my Win10 event viewer had (Also, the app will not open again):

Application: EDDI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.String)
   at EddiCompanionAppService.CompanionAppService.ShipFromProfile(System.Object)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(Newtonsoft.Json.Linq.JObject)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(System.String)
   at EddiCompanionAppService.CompanionAppService.Profile(Boolean)
   at EddiCompanionAppService.CompanionAppService..ctor()
   at EddiCompanionAppService.CompanionAppService.get_Instance()
   at Eddi.MainWindow.setStatusInfo()
   at Eddi.MainWindow..ctor(Boolean)
   at Eddi.MainWindow..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at System.Windows.Application.Run()
   at Eddi.App.Main()

**Comment by smeggysmeg** [comment] 2017-04-12 00:16
Same issue.

**Comment by rclough** [comment] 2017-04-12 04:15
+1

**Comment by geofwlkr** [comment] 2017-04-12 20:06
You must be tired of Me Too notices but Me Too...  
I have just realised how much I rely on EDDI when in game.

**Comment by Darkcyde13** [comment] 2017-04-12 20:17
This would appear to be due to ED 2.3 Companion App changes.  Until a new build of EDDI is released, deleting your %APPDATA%/Roaming/EDDI/credentials.json will allow EDDI to run again.  However, there will be limited functionality.  Don't try to log into the Companion App again, or you will have to delete the credentials.json again before EDDI will start the next time you try to run it.

Some people have attributed this problem to the new upgrade to Windows 10 Creators Updated.  However, I upgraded last week when it was first available to download from Microsoft, and both EDDI and ED2.2 worked perfectly on it, so I'm sure that the new Windows is not the cause.

**Comment by geofwlkr** [comment] 2017-04-12 20:28
I can confirm that. I also had EDDI working happily with the new version of Windows 10. I had been using it when ED decided to close the servers, when the ED update eventually loaded the problems started.

**Comment by Kraegge** [comment] 2017-04-12 22:42
I can confirm that it has nothing to do with the Windows update. I have the same problem since 2.3 went live, but have not yet updated Windows 10.

**Comment by Robert-Laverick** [comment] 2017-04-13 10:11
I've done a little digging, looks like the companion API isn't providing json data for ships in quite the same way, a few minor changes as well as a lot of the information for stored ships being missing, which causes problems.

I've done a first pass at hacking the code to work with 2.3, and it's at least able to open now, though it means you can only export your current ship to coriolis exporting others causes errors, and I've not used it extensivly yet, things that depends on ship setup could be broken else where too.

https://github.com/Robert-Laverick/EliteDangerousDataProvider/commit/e10546e51a7a95971d63a6ca8487ddd2317492fa

**Comment by GobleSt** [comment] 2017-04-13 15:16
EDDI broken here also.  

It was working in the BETA.  Currently VA shows the plugin initializing but it is not working and I am unable to open the companion app.  

This is also broken but was broken in BETA, also throwing exceptions:  https://github.com/Duke-Jones/ED-IBE  
This is working:  https://github.com/Marginal/EDMarketConnector/wiki

Windows 10 creators update.

**Comment by Robert-Laverick** [comment] 2017-04-13 16:36
Looks like my patch is actually just a duplication of work, TomasEkeli beat me to it with a pull request that's doing more or less the same things (still learning how github works, apologies for the learning curve showing) https://github.com/cmdrmcdonald/EliteDangerousDataProvider/pull/186

I've tested a bit today and it does seem functional with these patches, though there are issues with ship exports for stored ships (active ones seem to be working, but I've not done exhaustive testing)

**Comment by TomasEkeli** [comment] 2017-04-13 18:31
Until a new release is made you can drop in a replacement-file for the CompanionApp -library as described in the readme in this zip: https://www.dropbox.com/sh/kvevq3u9qbi9mm5/AAAHgcMdqmLh7sR4ZSbJOuQba?dl=0&preview=EDDI_commanders_fix.zip

**Comment by geofwlkr** [comment] 2017-04-13 21:04
Unfortunately after dropping in the replacement file and restoring the credentials.json file EDDI does not crash but it no longer gives system detail when you make a jump. Also whenever EDDI would be expected to give some form of audio response the Elite game suddenly stutters (presumably fighting EDDI for processor time).

**Comment by TomasEkeli** [comment] 2017-04-13 21:18
I've noticed that in the last few hours as well, @geofwlkr, but that's not this. It's been working fine for me for over 24 hours with the replacement. I suspect some other service has either changed their output or gone down. I'll look into it, I think - but I don't know what causes it.

**Comment by mikelimtw** [comment] 2017-04-14 02:13
You know, I'm kind of surprised CmdrMcDonald hasn't weighed in on this yet

**Comment by cmdrmcdonald** [comment] 2017-04-14 06:28
Apologies for the delay in providing a fix for this, I will address this issue today.  Please note that this due to undocumented changes in the Frontier API the following features will no longer be available:

  * engineer modifications when exporting to Coriolis
  * ability to export stored ships to Coriolis
  * information about the total and current amounts of fuel
  * information about the total and current amounts of cargo

Some of these items can be obtained in a different way to that how they are obtained today, and will be reinstated in a future patch.

**Comment by mikelimtw** [comment] 2017-04-14 06:31
I'm sort of surprised that FDev keeps doing this... making undocumented changes when there is such a huge community basically working for free to support them to make money

**Comment by Stevax** [comment] 2017-04-14 07:10
I think everyone realises it's down to Fdev end changes, I just think the amount of people logging the problem shows how popular your app is, I certainly miss it. Thanks for looking at it.

**Comment by cmdrmcdonald** [comment] 2017-04-14 12:11
This issue should be addressed with EDDI 2.2.3.  You can obtain this using the usual upgrade method or you can obtain it directly from https://www.mcdee.net/elite/EDDI.exe

**Comment by Darkcyde13** [comment] 2017-04-14 12:46
Logs in fine for me now. Thank you Cmdr. McDonald!

**Comment by geofwlkr** [comment] 2017-04-14 13:04
Magic! No problems, no stuttering and audio information restored. Thanks Cmdr.McDonald!

**Comment by jimbot70** [comment] 2017-04-14 17:25
Thank you for all of your work on this CMDR McDonald.

**Comment by rj16066** [comment] 2017-04-15 16:05
Thank you for the quick fix... Cheers

**Closed** 2017-04-19 12:56 UTC
