### ISSUE TITLE
Unable to open EDDI configuration

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#181] opened 2017-04-11 23:04 UTC
I am unable to open the EDDI configuration.  If I try to run EDDI standalone, it never opens.  VA loads the plugin, but if I use the config command it never opens the config window.

Trying to open EDDI from VA gives this error:
`2017-04-11T22:52:59 VoiceAttackPlugin:InvokeConfiguration [W] Show configuration window failed Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , String )
   at EddiCompanionAppService.CompanionAppService.ShipFromProfile(Object json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(JObject json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(String data)
   at EddiCompanionAppService.CompanionAppService.Profile(Boolean forceRefresh)
   at EddiCompanionAppService.CompanionAppService..ctor()
   at EddiCompanionAppService.CompanionAppService.get_Instance()
   at Eddi.MainWindow.setStatusInfo()
   at Eddi.MainWindow..ctor(Boolean fromVA)
   at EddiVoiceAttackResponder.VoiceAttackPlugin.<>c.<InvokeConfiguration>b__11_0()`

And trying to open EDDI standalone gives this error:
`2017-04-11T22:56:34 EDDI:.ctor [E] Failed to initialise Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at EddiCompanionAppService.CompanionAppService.ShipFromProfile(Object json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(JObject json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(String data)
   at EddiCompanionAppService.CompanionAppService.Profile(Boolean forceRefresh)
   at EddiCompanionAppService.CompanionAppService..ctor()
   at EddiCompanionAppService.CompanionAppService.get_Instance()
   at Eddi.EDDI..ctor()`

I tried deleting credentials.json and was able to get EDDI to open, but now I get the binder exception error inside EDDI on the credentials tab.

Here is the log: [eddi.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/914870/eddi.zip), I run with verbose logging on anyway :) I am running EDDI 2.2.2.

**Comment by folkdeezy** [comment] 2017-04-11 23:17
same issue.  cant get eddi to open

**Comment by Darkcyde13** [comment] 2017-04-11 23:18
I had this too.  I think it's because of the problem with the Companion App.  If you delete your 'credentials.json' file then EDDI should open again.  This is what I had to do.  Of course, until the App problem is sorted, some features of EDDI will not work.

**Comment by Darkcyde13** [comment] 2017-04-11 23:18
I had this too.  I think it's because of the problem with the Companion App.  If you delete your 'credentials.json' file then EDDI should open again.  This is what I had to do.  Of course, until the App problem is sorted, some features of EDDI will not work.

**Comment by rj16066** [comment] 2017-04-12 00:07
Same here.. Get the same thing, EDI will not open. I am on Win 10 and a Win 10 update did happen. I deleted EDDI and reinstalled it, but it gives me the same thing as the first post above.

**Comment by Ch4rli3G0rd0n** [comment] 2017-04-12 06:46
same issue since Elite 2.3 update. EDDI standalone won't open, VoiceAttack will load it but then it doesn't work in game. Same issue with EDDI 2.2 and EDDI 2.2.2.

**Comment by sammyf** [comment] 2017-04-12 06:51
just to chime in : same problems. Thanks Dark Cycle for pointing out which json file should be deleted!

**Comment by rj16066** [comment] 2017-04-12 11:29
Where is this credential file located?

**Comment by sammyf** [comment] 2017-04-12 13:52
rj16066 : in "%APPDATA%/EDDI"

**Comment by rj16066** [comment] 2017-04-12 17:56
Thanks, will try it tonight.

Cheers

**Comment by Darkcyde13** [comment] 2017-04-12 20:08
Until EDDI is updated, don't try to log into the Companion App.  If you do try, you will need to delete the %APPDATA%/Roaming/EDDI/credentials.json file before EDDI will run again.

**Comment by TomasEkeli** [comment] 2017-04-13 18:31
Until a new release is made you can drop in a replacement-file for the CompanionApp -library as described in the readme in this zip: https://www.dropbox.com/sh/kvevq3u9qbi9mm5/AAAHgcMdqmLh7sR4ZSbJOuQba?dl=0&preview=EDDI_commanders_fix.zip

**Comment by cmdrmcdonald** [comment] 2017-04-14 06:20
Duplicate of #179

**Closed by cmdrmcdonald** 2017-04-14 06:20 UTC
