### ISSUE TITLE
EDDI 2.0.0.b5 is crashing VoiceAttack when autoresponding

### ISSUE THREAD

**Issue by tastler** [cmdrmcdonald/EliteDangerousDataProvider#34] opened 2016-10-22 12:17 UTC
VA version: 1.5.12.24 
E:D Horizons Vanilla and Guardians BETA7

Whenever I jump, land, or enter supercruise, VoiceAttack is crashing. 

[eddilog.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/545762/eddilog.zip)

**Comment by cmdrmcdonald** [comment] 2016-10-24 08:52
Thank you for reporting this, I've made some changes to the code to catch what I believe is the cause of this error and released a beta 6 version.  Please could you give this a try and let me know if it fixes your issue?

**Comment by tastler** [comment] 2016-10-24 17:59
Hi,
thanks for the quick fix! So far, I wasn't able to reproduce the reported issue with version 2.0.0.b6

Cheers

**Comment by tastler** [comment] 2016-10-24 19:29
After playing for an hour, it only crashed VA once on a system-jump, so far

**Comment by tastler** [comment] 2016-10-24 19:42
Seems like after one crash, it is instable again and crashes VA in any instance on jumps, scans etc.
Note: sometimes - when not crashing it says the sentences without the shipname. As if the variable was not set, or properly initialized. Please find attached, the new logfile.
[eddi.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/548787/eddi.zip)

**Comment by tastler** [comment] 2016-10-24 20:02
closing all applications, including E:D & Launcher, and killing the IVONA center process via task manager seems to help.

**Comment by cmdrmcdonald** [comment] 2016-10-27 08:03
Fixed in production release.

**Closed by cmdrmcdonald** 2016-10-27 08:03 UTC
