### ISSUE TITLE
ship.cargocapacity returning always 0

### ISSUE THREAD

**Issue by Pryss** [cmdrmcdonald/EliteDangerousDataProvider#258] opened 2017-07-30 11:01 UTC
Hello,

 It's in the title, it don't work with the VA commands.
or maybe I have missed something : 

{if ship.cargocapacity > 0:
       
       {if ship.cargocarried = 0:
        La soute est vide
        |elif ship.cargocarried >0:
        Nous transportons {P(ship.cargocarried)} tonnes de fret sur {P(ship.cargocapacity)}
        }
    
    |elif ship.cargocapacity = 0:
        Nous n'avons pas de soute
}

**Comment by Darkcyde13** [comment] 2017-07-30 19:11
'ship.cargocarried' is bugged and always results in 0. We are not sure if this will be fixed anytime soon.

'ship.cargocapacity' will not update immediately if you fit or remove cargo racks.  It seems this only updates when you swap ships or load your game, but it does work once it has updated.

**Comment by Pryss** [comment] 2017-08-01 18:29
Thanks for your answer.

By the way, do you know if there is a site where it can be possible to share personnalities ? Or to get some made by others ? I'm currently working on a French personnality, and would like to share it with other players.

**Comment by Darkcyde13** [comment] 2017-08-02 19:20
There is a site called Snafets (http://snafets.de/elite/eddi_scripts/) that hosts files. The Elite section doesn't have many though, only 6.

Alternatively, you can post to the FDev forums, either in the main EDDI thread, or a second one (where I post my personality).  

The main thread is - https://forums.frontier.co.uk/showthread.php/294579-EDDI-Windows-app-for-immersion-and-more

The second one is - https://forums.frontier.co.uk/showthread.php/311614-EDDI-Scripts-and-EDDI-enabled-VA-Commands-Thread

**Comment by Pryss** [comment] 2017-08-02 21:23
Thanks a lot.

**Comment by Tkael** [comment] 2017-08-04 18:51
This is a duplicate issue. Since the problem is already reported here: https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/62, would you please close this duplicate so that we can keep the list clean? Thanks!

**Closed as completed** 2017-08-06 05:24 UTC
