### ISSUE TITLE
eddi can't connect to companion app

### ISSUE THREAD

**Issue by EmporiaHall** [cmdrmcdonald/EliteDangerousDataProvider#184] opened 2017-04-12 08:01 UTC
![2017-04-12](https://cloud.githubusercontent.com/assets/27338599/24947390/7c0da664-1f5e-11e7-9bf1-349b40d10cf8.png)

**Comment by Darkcyde13** [comment] 2017-04-12 16:44
Please don't open separate issues for ones that already exist. This is a duplicate issue of #179. This is due to ED Horizons 2.3 App changes.

**Comment by TomasEkeli** [comment] 2017-04-13 18:32
Until a new release is made you can drop in a replacement-file for the CompanionApp -library as described in the readme in this zip: https://www.dropbox.com/sh/kvevq3u9qbi9mm5/AAAHgcMdqmLh7sR4ZSbJOuQba?dl=0&preview=EDDI_commanders_fix.zip

**Comment by GobleSt** [comment] 2017-04-13 20:17
Works for me!  Thanks!

**Comment by cmdrmcdonald** [comment] 2017-04-14 06:21
Duplicate of #179

**Closed by cmdrmcdonald** 2017-04-14 06:21 UTC
