### ISSUE TITLE
Jump event (Netlog reader) not working anymore

### ISSUE THREAD

**Issue by carlostib** [cmdrmcdonald/EliteDangerousDataProvider#116] opened 2017-02-03 02:07 UTC
I noticed today, after not connecting for some days that Jump events (when EDDI extracts information on the next system while in witch space( is not working anymore. I checked in EDDI configurator and Netlogs directory is correct and has not changed. Have any of you experienced the same?

**Comment by cmdrmcdonald** [comment] 2017-02-03 11:59
Please could you enable verbose logging, jump to a new system, then disable verbose logging again and send the logs?  Buttons to do this are on the initial tab of the main EDDI UI.

**Comment by Nalsister** [comment] 2017-02-14 18:43
It is a Google translation. I am sorry that I am not good at English.
I also have similar problems.
When entering EDDI Jumping with FSD Drive, Voice Attack will CTD.
It happens many times when CTD happens, but never happens when it does not happen.
My friend has no problem at all with the same setting, but what is the cause of the problem?
Please let me know how EDDI Jumping will not be CTD.

**Comment by carlostib** [comment] 2017-02-14 19:19
Hi All,
I know what was the issue, I go back and forth between Linux and Windows partitions and for some reason, BIOS date is changed everytime I boot to Windows, like 7 hours more from actual time. So, the journal and log files were being created with that "future" time, then when I correct the time in Windows, then EDDI is not able to see the changes as is still monitoring the most "recent" log files, meaning the future date/time generated before when first launching the game with the wrong date/time. So, after I deleted manually the journal and all log files with that erroneous date-time, then EDDI was able to work as usual. Thanks all for your support.

**Comment by Nalsister** [comment] 2017-02-15 04:24
I am using Windows 10.
And I live in Japan.
We confirmed the BIOS time, but the time was not wrong.
Which journal and log files were manually deleted?
C: \ Users \ xxx \ AppData \ Roaming \ EDDI \ eddi.log?
I am happy that you can tell me in detail.

**Comment by cmdrmcdonald** [comment] 2017-02-20 16:38
Addressed by user

**Closed by cmdrmcdonald** 2017-02-20 16:38 UTC
