### ISSUE TITLE
Companion App issue

### ISSUE THREAD

**Issue by Jonono999** [cmdrmcdonald/EliteDangerousDataProvider#185] opened 2017-04-12 09:02 UTC
After upgrading Windows, the Companion App doesn't work anymore.
![companionappissue](https://cloud.githubusercontent.com/assets/27341698/24949897/6ffacd32-1f6f-11e7-819c-85ba2acb43d8.JPG)

**Comment by Rodasson** [comment] 2017-04-12 11:37
Jep- same here ...

**Comment by Kraegge** [comment] 2017-04-12 14:17
I have the same problem.

**Comment by shaunpond** [comment] 2017-04-12 16:00
Same here - EDDI was crashing in .net, so I uninstalled and reinstalled. When I tried to enter the companion app details I git a similar crash to the OP 
![image](https://cloud.githubusercontent.com/assets/20541580/24967284/7c5bf90c-1fa1-11e7-9d60-13c2acf82e5f.png)

**Comment by RoundAbout2Space** [comment] 2017-04-12 16:11
...me2
Did update on Elite Dangerous / Horizon 2.3 today...
Got EDDI 2.2.2 update ...
Had to setup companion app...
Got same result...
Using Windows 10 Pro Version 1607 OS Build 14393.969

**Comment by Darkcyde13** [comment] 2017-04-12 16:44
Please don't open separate issues for ones that already exist. This is a duplicate issue of #179. This is due to ED Horizons 2.3 App changes.

**Comment by TomasEkeli** [comment] 2017-04-13 18:32
Until a new release is made you can drop in a replacement-file for the CompanionApp -library as described in the readme in this zip: https://www.dropbox.com/sh/kvevq3u9qbi9mm5/AAAHgcMdqmLh7sR4ZSbJOuQba?dl=0&preview=EDDI_commanders_fix.zip

**Comment by cmdrmcdonald** [comment] 2017-04-14 06:21
Duplicate of #179

**Closed by cmdrmcdonald** 2017-04-14 06:21 UTC
