### ISSUE TITLE
Passing Variables from Scripts

### ISSUE THREAD

**Issue by Castleberg** [cmdrmcdonald/EliteDangerousDataProvider#31] opened 2016-10-08 23:37 UTC
Hey, I moved this to a new issue so it might be more helpful to others. 

I was looking through the new speech responder tab, and feel like there is a ton of potential here, but not quite sure how to tap into it. I read through the documentation at http://r3c.github.io/cottle/#toc-2 which was helpful, but I'm still not sure how to pass information from the plugin to variables in VA.

Example:
Lets say I want to set a variable "StationID" to whatever my ship currently was, and then use this to automate trades based on that location. My current thought was I could pass the 'EDDI docked station' plugin variable to "StationID", which I could then use to run my commands. (Although I am a little confused between 'EDDI docked station' and the script 'location' when docked....

However, calling {TXT:EDDI docked station} simply reads "EDDI docked station".  likewise {TXT:((EDDI docked station))} does the same.  So I guess my question is 2 fold...

1) How can I call on a variable / script from within VA (i.e. set StationID to {TXT:((EDDI docked station))}
and
2) How can I set variables / call on variables of VA from WITHIN EDDI SCRIPT. (i.e. 

 You are
{if event.docked:
    docked at {P(event.body)}
    **{set StationID to {P(event.body)}**
}

Sorry if that was vague, but I think you get an idea of what I'm going for. I would basically like to make a script that gives me all the variables I need to Set up my preferred trading routes, so every time I land at a station, it pulls the information, knows what station I am at, checks my inventory (if possible), sells my cargo, buys my new cargo, and off I go.  Right now I do this by assigned each station a "alpha, bravo, charlie, etc." designation, then when I land I just say, "Trade Alpha", which automates all my trading, but have been salivating over the possiblility of it being able to automatically pull this info from EDDI to know what to do whatout me telling it...Just having a hard time with the syntax to get there...

**Comment by cmdrmcdonald** [comment] 2016-10-09 01:00
EDDI sets event variables in VoiceAttack automatically, so for your example you would create a VoiceAttack command with the name `((EDDI docked))`.  This will be called whenever the docked event is triggered, and to access (for example) the station at which you docked you can use `{TXT:EDDI docked station}`, as below.

![cap](https://cloud.githubusercontent.com/assets/16817420/19216836/11b1c3d0-8dc4-11e6-994f-994f6964c4cd.PNG)

**Comment by Castleberg** [comment] 2016-10-09 14:27
Wow. I just lost my whole post.  Shoot....  Ok, I'll try to breifly recap / summerize....((Sign))

I seem to be having a problem with script activation, and syntax here.

1) Script Activation
![image](https://cloud.githubusercontent.com/assets/22641692/19220863/3be01788-8e05-11e6-8bca-491e1274575f.png)

and

![image](https://cloud.githubusercontent.com/assets/22641692/19220864/457acfa4-8e05-11e6-82ad-6f704f738165.png)

In the above example, despite the speech responder script being enabled (and functioning if I hit test), and having a VA command ((EDDI docked)), neither runs.

I have been operating under the assumption that the Speech Responder scripts are automatically triggered by events in game by EDDI. (I assume any scripts we create from scratch are limited to the names listed in the stock speech responder, and are called by EDDI by name, as I see nothing in the script that sets a trigger event.  I.e. Behind the scenes EDDI says something like, "If event.ship.docked = true, run SpeechResponder.Docked". and any script we create would need that same name, and be automatically launched when said event happends?  For now I'm avoiding new scripts and just modifying exiting ones for that very reason, as I'm not sure how to launch them...

With that in mind, and taking a look at the above screens, I am perplexed that neither the SpeechResponder script runs, nor the VA Command. 

2) Variable managment
I am probably just an idiot here...but it seems like the documentation is not consistant with how to access information.  
Take this simple example:
![image](https://cloud.githubusercontent.com/assets/22641692/19220950/4f16f4a0-8e07-11e6-91ad-624f349d1109.png)

when running this script, a single instance of Commander name is given ( {cmdr.name} ), and a single instance of ship callsign ( {ShipCallsign()} ). Station name is not reported in either case ( {Station.name} OR {StationName()} ).

The documetation states:

>  Commander
> 
>  information is available under the cmdr object.
> ...
> - name the Commander's name"
> 
> "Information about your current ship is available under the ship object.
> ...
> - callsign the callsign for the ship"

and 

> Station
> ...
> - name the name of the station

with the 

> Event 
> Triggered when your ship requests docking at a station or outpost.
> ...
> - station The station at which the commander has requested docking

being something I'm not sure how to call, referrance, or otherwise utilize.

But with the first three examples, I would expect that the commander name would be called either by {cmdr name}, {cmdr.name}, {CmdrName}, or {CmdrName()} (the documentation isn't really clear, and having an example for each would be great. i.e. 

> Commander
> Commander information is available under the cmdr object.
> 
> **Example: {cmdr.name} will result in the commander name.**
> 
> Any values might be missing, depending on EDDI's configuration.
> 
> - name the Commander's name
> 

Anyway, {cmdr.name} works.  Great.  Yet, attempting to keep consistant, and write "{ship.callsign} does nothing.  In this case, {ShipCallsign()} is the only thing that will return the callsign.  Hmmm. 

Again, I'm probably just an idiot. but I'm scratching my head on how to call the variables in the scripts, as it doesn't seem to be consistant with the documentation.

Lastly, and I touched on this before...

How do I call that variable externally in voice attack? Reviewing the EDDI information commands is very helpful, and I can see that {TXT:Name} is the VA syntax to retrieve the script equivalent of "{cmdr.name}". Yet it seems there are several variables in the script that are not available. 

For example:  commodity.stock, commodity.buyprice, or, more importantly {best.name}

Is there a way to set an internal variable of the script to a external VA variable that we can then call through VA?

Thanks again, your promptness and responsiveness have been really appreciated and admired.  
I hope this was clear. Having to retype always leads to loss of information, but I tried to be as clear as I could...

**Comment by Castleberg** [comment] 2016-10-09 14:39
Oh, as a side note (and adding to my confusion)

You stated above that 

> EDDI sets event variables in VoiceAttack automatically, so for your example you would create a VoiceAttack command with the name ((EDDI docked)). This will be called whenever the docked event is triggered, and to access (for example) the station at which you docked you can use {TXT:EDDI docked station}

Yet, the following does nothing for me:

![image](https://cloud.githubusercontent.com/assets/22641692/19221156/b3308b1e-8e0b-11e6-9745-e34a82db1627.png)

Searching for the variable you mentioned "EDDI docked station" in the EDDI information reveals nothing:
![image](https://cloud.githubusercontent.com/assets/22641692/19221163/d351b2ce-8e0b-11e6-8c63-f06f21a5640b.png)

, except "{TXT:Last station name}"  (which for me results only "Not set").

So I am not sure where the "EDDI docked station" syntax is coming from. 

I can only assume that it is referrancing the event I didn't know what to do with above.

I.e. EDDI docked is the event , station is a variable set/associated with that event. So in VA saying, "{TXT:EDDI docked station} should give the station, associated with the event docked.

By that logic I could also say, "{TXT:EDDI Jumped system}" or "{TXT:EDDI Jumped security}"  Is that fair?

**Comment by cmdrmcdonald** [comment] 2016-10-09 17:12
Okay there are various things here.

First off, the speech responder and the VoiceAttack responder are separate pieces of code and do not interact.  So we need to separate out questions about them as otherwise things will become complex.

I'll start with the questions for the speech responder.  There are a number of objects that are exposed in speech responder scripts, for example details of your current ship are exposed in the ship object, and the name of your ship is set in the ship.name value.  The problem is, sometimes people don't set the name of their ship and sometimes they create a separate phonetic name for their ship so that the text-to-speech engine pronounces it correctly.  This means that if you want to obtain a correct spoken name for your ship you'll have to jump through hoops like:

    {if ship.phoneticname:
        {ship.phoneticname}
    |elif ship.name:
        {ship.name}
    |else:
        your ship
    }

which isn't a lot of fun to keep writing everywhere, hence the introduction of the ShipName() feature.  ShipName() also takes an optional parameter of the local ID of the ship that you want to provide so that you can generate names for ships in your shipyard, which is useful when transferring and swapping ships.

There are probably some inconsistencies in what is available as a function and what is available as a direct variable; the ship's callsign is a good example of this and I'll fix it so that it is visible (although it's somewhat academic as it's rare that someone would want the textual representation of the callsign rather than the phonetic one).

Note that all variables and objects are lower-case, and all functions are capitalised, so in your case the attempt to use {Station.*} to access station information won't work.  {station.name} should work in this case, although as mentioned in the document you should generally use {P(station name}) as that will attempt to turn any hard-to-pronounce parts of the name in to phonetics for a better result.

Looking at the code there is a vital piece of information missing about the event variables, specifically that they are all in the 'event' object.  So for the 'Docked' event the station name where you just docked is in 'event.station' (again I'll fix this in the code).

Does this address your questions for the speech responder?  If not then please let me know, if so we'll move on to the VoiceAttack responder.

And thank you for taking the time to test this and provide great feedback.  It's showing up both bugs in the code and inadequacies in the documentation, which is a massive help.

**Comment by Castleberg** [comment] 2016-10-09 19:29
No problem. I very much appreciate your work and responsiveness--anything I can do to make things better for all!

Ah, ok that makes sense. And I guess I would have figured that out if I had paid more attention to the docked script.  You did call the event.station variable in your random statement.  My bad.

So, to make sure I understand, when an event is triggered, EDDI automatically populates the event variables, which are then called in the script (which is also automatically run).  

So if I wanted to have it report, "you are enroute to ||System||" using the jumping script, I would do 

something like: 
You are enroute to {event.system}.

which in this case should be equivalent to:
You are enroute to {System.name}.

I got that about right?

If so, I think I'm ready for the Voice attack part based on your post.  

Feel free to omit the entire next portion, as it might be throwing you off-track.  I can always get back to it :)

Although, a nagging question in the back of my mind (that perhaps you will cover shortly), is how can I create variables and pull that information in Voice attack (or am I just limited to the built in ones).

Example: Say I was trading, and wanted to store the last 10 prices for a commodity, to be recalled later.  Or to keep inline with our current example, I wanted to keep the last 10 systems recorded. Something like:

if system.tracker = 1
system.one = {system.name}
system.tracker = system.tracker+1
elseif system.tracker = 2
system.two = {system.name}
system.tracker=system.tracker+1
.....
elseif system.tracker = 10
system.ten = {system.name}
system.tracker=1

I know I'm mixing code types there, sorry, but you get the point.  Random example, but the point being, are we capable of setting a variable / storing it, and then utilizing it later, or passing it through to Voice attack as a custom variable?

**Comment by cmdrmcdonald** [comment] 2016-10-20 08:46
I think I covered this on the forums, but the flow of information from EDDI to VoiceAttack is one-way.  VoiceAttack itself can store variable information in its profile so that it is persistent, but that's something that is worth discussing on the VoiceAttack forums rather than here.

**Comment by Castleberg** [comment] 2016-10-22 03:26
I'm very comfortable with voice attack, and variable management there-in.

My specific question / concern was regarding to passing variables from EDDI TO Voice attack.

Namely, I know I can reference the standard Eddi variables listed on the website. But the new implementation of eddi with the responder tab, and the ability to customize our own scripts leads me to ponder the possibilities...

What I am trying to discern, is if I can do an algorithm in the responder script, which I can do calculations / comparisons on and then save something to a custom output variable that I can then call from voice attack (besides the set ones on the website)

I hope I'm making my question clear?

**Comment by cmdrmcdonald** [comment] 2016-10-22 08:28
Responder scripts are self-contained, the only output from them is a single string value (which is then fed directly to the speech synthesiser).

In theory it would be possible to create a separate system that could be run a script and provide the output value to VoiceAttack as a variable, but it would require various changes to the responder and, more importantly, would confuse most people using EDDI as they would be expecting the responder scripts to be spoken rather than provide utility methods.  I'll have a look to see if I can put something like this in place in some way directly within the VA plugin.

**Comment by sabreqld** [comment] 2016-11-12 23:27
In a previous version of EDDI, I was able to manipulate the Voice Attack system jump section so that when it was first jump time in a system ever, it would automatically hold down left CTRL and scan the system after a 10 second wait.
Is this possible now?
Thanks for your time and expertise.

**Comment by cmdrmcdonald** [comment] 2016-12-29 21:34
EDDI 2.1 provides the ability to set state in one responder and make it available in others.  Responders run asynchronously, so no guarantees on what state information is available in any given responder, but for long-term items such as counting it should work fine.

**Closed by cmdrmcdonald** 2016-12-29 21:34 UTC
