### ISSUE TITLE
EDDI ot working

### ISSUE THREAD

**Issue by RedBaron1947** [cmdrmcdonald/EliteDangerousDataProvider#187] opened 2017-04-12 18:22 UTC
EDDI not working 

![eddi issue](https://cloud.githubusercontent.com/assets/20424977/24973014/32c2d3b0-1fb5-11e7-8a09-ad97fd5ac41f.png)
From:

jurgenmitch1947@gmail.com

**Comment by Darkcyde13** [comment] 2017-04-12 19:54
Please don't open separate issues for ones that already exist. This is a duplicate issue of #179. This is due to ED Horizons 2.3 App changes.

**Comment by TomasEkeli** [comment] 2017-04-13 18:32
Until a new release is made you can drop in a replacement-file for the CompanionApp -library as described in the readme in this zip: https://www.dropbox.com/sh/kvevq3u9qbi9mm5/AAAHgcMdqmLh7sR4ZSbJOuQba?dl=0&preview=EDDI_commanders_fix.zip

**Comment by cmdrmcdonald** [comment] 2017-04-14 06:21
Duplicate of #179

**Closed by cmdrmcdonald** 2017-04-14 06:21 UTC
