### ISSUE TITLE
Plugin execution exception: Error reading JObject...

### ISSUE THREAD

**Issue by Osprey101** [cmdrmcdonald/EliteDangerousDataProvider#33] opened 2016-10-18 14:47 UTC
9:38:56 PM - Plugin execution exception: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 6.

Suggestions?

**Comment by cmdrmcdonald** [comment] 2016-10-18 23:14
I'll need a bit more information.  First off, which version of EDDI are you running?  And where did you find this error?  Does it happen all of the time or was it a one-off?

The %APPDATA%\EDDI\EDDI.log might have more information, so ou can also post a link to it here and I will take a look

**Comment by Osprey101** [comment] 2016-10-19 00:30
Just downloaded EDDI so I am assuming it is the newest version. Also have the newest version of Voice Attack Beta.
That error came up as soon as I gave the command Ship Handover Confirmed and then repeated that basic error each time it tried to call up EDDI.
When I just went and tried it now to be sure I was giving correct information, it now says "Unable to invoke plugin, plugin not valid for this version of Voice Attack.
I have Voice Attack v1.5.12.27
No clue how to post a link to a file residing on my computer (%APPDATA%\EDDI\EDDI.log).
Did you want me to email it somewhere?
Thanks!

**Comment by Osprey101** [comment] 2016-10-20 00:41
Do you plan on updating this to work with the newest version of Voice Attack? I would really like to use this but the version of Voice Attack you used is no longer available from Voice Attack.
If you do not plan on updating this, which version of Voice Attack will run it and where can I download that version?

**Comment by cmdrmcdonald** [comment] 2016-10-20 08:43
It sounds like you are running EDDI 1, which is not compatible with the new version of VoiceAttack.  VoiceAttack changed their plugin architecture, which is quite possibly what is causing your problem.

Remove your existing EDDI installation and try the EDDI 2 beta at http://www.mcdee.net/elite/EDDI.exe  Instructions on how to use it at are available in the UI, just fire up the EDDI.exe when you have finished installing it.

**Comment by Osprey101** [comment] 2016-10-21 01:04
Well how the heck can I think you?
I think we got it!
I don't get any verbal reply with the command "Ship Handover Confirmed",, but I do get system info when jumping. I am sure once I play with things a bit, it should all come together.
Thank you again. This add on is very cool and puts everyone one step closer to piloting their ships like a captain instead of and oarsman. :+1:

**Comment by Wotherspoon** [comment] 2016-10-21 21:47
I had the same problem after a clean install of EDDI. The problem is that if you search Google for EDDI, you get a Frontier Forums entry by "jgm" dated 23/1/2016 that links to http://www.mcdee.net/elite/EDDI.zip as the version of EDDI to download. That link gets you 1.4.0 (which sounds sparkly and new because the GitHub page says 1.3.0 is the latest version). Turns out they're both wrong. Thanks for clarifying - after downloading the 2 beta from your link above I now have a working EDDI. And I can see that "ship handover complete" is no longer a recognised command!

**Comment by Osprey101** [comment] 2016-10-22 02:16
Yeah, wasn't sure if that was a critical command to sync everything or not.

**Comment by Wotherspoon** [comment] 2016-10-22 09:25
@Osprey101 I think it's just a test to make sure everything's working. Best way to find out now is jump to supercruise. EDDI didn't notice when I changed ships last night though: it kept calling my Adder a Cobra Mk III. There are so many cool features, though, like the list of ships, and the feeds to/from EDSM. Great program.

**Comment by cmdrmcdonald** [comment] 2016-10-24 08:54
The issue with EDDI being unaware of the ships changing is down to it being a manual command in EDDI 1.  EDDI 2 which will be released tomorrow along with Elite 2.2, should do this automatically.

**Comment by cmdrmcdonald** [comment] 2016-10-27 08:04
EDDI 2 is now released.

**Closed by cmdrmcdonald** 2016-10-27 08:04 UTC
