### ISSUE TITLE
"Unexpected Problem" when inputting Verification Code

### ISSUE THREAD

**Issue by PaleGringo** [cmdrmcdonald/EliteDangerousDataProvider#182] opened 2017-04-12 02:41 UTC
Was in process of reinstallation of EDDI 2.2.2 to default location.  Went to Companion App tab and entered email address and password, clicked Next.  Went to email, copied verification code from Frontier and pasted it in EDDI application, clicked Next.  Following message appears in the app and will not let me reauthenticate:

![image](https://cloud.githubusercontent.com/assets/17752908/24938837/7d1345a2-1eee-11e7-9658-881cc85bd1ac.png)

(I did a screenshot because I was not able to find a log file to copy and paste that from)

I just updated Windows 10 to Version 1607 (OS Build 14393.1066).  Typically, I have EDDI launch via EDFX 3.0.1.5 though the problem is manifest if I launch EDDI on its own or if I uninstall and reinstall from the executable on github.

**Comment by M0d3u5** [comment] 2017-04-12 03:35
I am also having this exact same issue. Just to second that this is not isolated.

**Comment by Darkcyde13** [comment] 2017-04-12 16:43
Please don't open separate issues for ones that already exist. This is a duplicate issue of #179. This is due to ED Horizons 2.3 App changes.

**Comment by TomasEkeli** [comment] 2017-04-13 18:32
Until a new release is made you can drop in a replacement-file for the CompanionApp -library as described in the readme in this zip: https://www.dropbox.com/sh/kvevq3u9qbi9mm5/AAAHgcMdqmLh7sR4ZSbJOuQba?dl=0&preview=EDDI_commanders_fix.zip

**Comment by PaleGringo** [comment] 2017-04-14 02:19
Thanks for the patch, @TomasEkeli .  Appreciate the effort, and it helped my issue out.

**Comment by cmdrmcdonald** [comment] 2017-04-14 06:21
Duplicate of #179

**Closed by cmdrmcdonald** 2017-04-14 06:21 UTC
